package com.syntacticsugar.vooga.util.dirview;

import java.io.File;

public interface IDirectoryViewer<T> {

	/**
	 * Builds a viewable structure of a File directory using the simplified
	 * data representations generated by the IConverter interface. Usually
	 * implemented alongside UI elements (JavaFX Nodes).
	 * @param directory
	 * @param fileConverter
	 * @return 
	 */
	public void showDirectoryContents(File directory, IConverter<T> fileConverter);
	
}
